### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by ayoungethan** [elementary/settings-daemon#51] opened 2022-03-15 19:00 UTC
### What Happened?
```

show_signal_msg: 11 callbacks suppressed
[   36.806486] io.elementary.s[1447]: segfault at 10 ip 000055aa87902fb2 sp 00007ffc17adde98 error 4 in io.elementary.settings-daemon[55aa87900000+c000]
[   36.806502] Code: 5d c3 66 0f 1f 44 00 00 f3 0f 1e fa 55 48 85 ff 74 26 48 89 fd e8 ee fe ff ff 48 8b 7d 00 48 89 c6 e8 02 dc ff ff 48 89 ef 5d <48> 8b 40 10 ff e0 0f 1f 84 00 00 00 00 00 48 8d 15 28 91 00 00 48
```

### Steps to Reproduce

Not sure how to reproduce. This is on a dual-user system (one standard and one admin user)

### Expected Behavior

No crash :)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-06-30 17:41
I'll close this as incomplete because no similar issues were reported and no steps to reproduce provided.

**Closed by lenemter** 2023-06-30 17:41 UTC
